// Code generated by Slice Machine. DO NOT EDIT.

import HoroscopeRad from "./HoroscopeRad/index.svelte";
import Members from "./Members/index.svelte";

export const components = {
  horoscope_rad: HoroscopeRad,
  members: Members,
};
