// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Content for Horoscoperad documents
 */
interface HoroscoperadDocumentData {
  /**
   * title field in *Horoscoperad*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: horoscoperad.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * zodiacicon field in *Horoscoperad*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: horoscoperad.zodiacicon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  zodiacicon: prismic.ImageField<never>;

  /**
   * explanationtext field in *Horoscoperad*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: horoscoperad.explanationtext
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  explanationtext: prismic.KeyTextField;

  /**
   * horoscopecard field in *Horoscoperad*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: horoscoperad.horoscopecard
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  horoscopecard: prismic.ImageField<never>;
}

/**
 * Horoscoperad document from Prismic
 *
 * - **API ID**: `horoscoperad`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HoroscoperadDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HoroscoperadDocumentData>,
    "horoscoperad",
    Lang
  >;

/**
 * Content for squadmembers documents
 */
interface SquadmembersDocumentData {
  /**
   * name field in *squadmembers*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: squadmembers.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * memberImage field in *squadmembers*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: squadmembers.memberimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  memberimage: prismic.ImageField<never>;

  /**
   * horoscope field in *squadmembers*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: squadmembers.horoscope
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  horoscope: prismic.RichTextField;

  /**
   * age field in *squadmembers*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: squadmembers.age
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  age: prismic.NumberField;
}

/**
 * squadmembers document from Prismic
 *
 * - **API ID**: `squadmembers`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SquadmembersDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SquadmembersDocumentData>,
    "squadmembers",
    Lang
  >;

export type AllDocumentTypes =
  | HomeDocument
  | HoroscoperadDocument
  | SquadmembersDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      HoroscoperadDocument,
      HoroscoperadDocumentData,
      SquadmembersDocument,
      SquadmembersDocumentData,
      AllDocumentTypes,
    };
  }
}
