// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice = MembersSlice | HoroscopeRadSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * titel field in *home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.titel
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titel: prismic.RichTextField;

  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Content for HoroscopeIntroduction documents
 */
interface HoroscopeintroductionDocumentData {
  /**
   * title field in *HoroscopeIntroduction*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: horoscopeintroduction.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * horoscopeImage field in *HoroscopeIntroduction*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: horoscopeintroduction.horoscopeimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  horoscopeimage: prismic.ImageField<never>;

  /**
   * horoscopeTitle field in *HoroscopeIntroduction*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: horoscopeintroduction.horoscopetitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  horoscopetitle: prismic.RichTextField;

  /**
   * aboutHoroscope field in *HoroscopeIntroduction*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: horoscopeintroduction.abouthoroscope
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  abouthoroscope: prismic.KeyTextField;

  /**
   * moreStudents field in *HoroscopeIntroduction*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: horoscopeintroduction.morestudents
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  morestudents: prismic.RichTextField;

  /**
   * memberImage field in *HoroscopeIntroduction*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: horoscopeintroduction.memberimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  memberimage: prismic.ImageField<never>;
}

/**
 * HoroscopeIntroduction document from Prismic
 *
 * - **API ID**: `horoscopeintroduction`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HoroscopeintroductionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HoroscopeintroductionDocumentData>,
    "horoscopeintroduction",
    Lang
  >;

/**
 * Content for Horoscoperad documents
 */
interface HoroscoperadDocumentData {
  /**
   * title field in *Horoscoperad*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: horoscoperad.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * zodiacicon field in *Horoscoperad*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: horoscoperad.zodiacicon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  zodiacicon: prismic.ImageField<never>;

  /**
   * explanationtext field in *Horoscoperad*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: horoscoperad.explanationtext
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  explanationtext: prismic.KeyTextField;

  /**
   * horoscopecard field in *Horoscoperad*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: horoscoperad.horoscopecard
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  horoscopecard: prismic.ImageField<never>;
}

/**
 * Horoscoperad document from Prismic
 *
 * - **API ID**: `horoscoperad`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HoroscoperadDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HoroscoperadDocumentData>,
    "horoscoperad",
    Lang
  >;

/**
 * Content for squadmembers documents
 */
interface SquadmembersDocumentData {
  /**
   * name field in *squadmembers*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: squadmembers.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * memberImage field in *squadmembers*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: squadmembers.memberimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  memberimage: prismic.ImageField<never>;

  /**
   * horoscopeImage field in *squadmembers*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: squadmembers.horoscopeimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  horoscopeimage: prismic.ImageField<never>;

  /**
   * horoscope field in *squadmembers*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: squadmembers.horoscope
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  horoscope: prismic.SelectField<
    | "Ram"
    | "Stier"
    | "Tweelingen"
    | "Kreeft"
    | "Leeuw"
    | "Maagd"
    | "Weegschaal"
    | "Schorpioen"
    | "Slangendrager"
    | "Boogschutter"
    | "Steenbok"
    | "Waterman"
    | "Vissen"
  >;

  /**
   * age field in *squadmembers*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: squadmembers.age
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  age: prismic.NumberField;

  /**
   * favoriteCodeLanguage field in *squadmembers*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: squadmembers.favoritecodelanguage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  favoritecodelanguage: prismic.RichTextField;

  /**
   * squad field in *squadmembers*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: squadmembers.squad
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  squad: prismic.BooleanField;

  /**
   * ProfielCardLink field in *squadmembers*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: squadmembers.profielcardlink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  profielcardlink: prismic.LinkField;
}

/**
 * squadmembers document from Prismic
 *
 * - **API ID**: `squadmembers`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SquadmembersDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SquadmembersDocumentData>,
    "squadmembers",
    Lang
  >;

export type AllDocumentTypes =
  | HomeDocument
  | HoroscopeintroductionDocument
  | HoroscoperadDocument
  | SquadmembersDocument;

/**
 * Primary content in *HoroscopeRad → Items*
 */
export interface HoroscopeRadSliceDefaultItem {
  /**
   * rads field in *HoroscopeRad → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: horoscope_rad.items[].rads
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  rads: prismic.ContentRelationshipField<
    "horoscoperad" | "horoscopeintroduction"
  >;
}

/**
 * Default variation for HoroscopeRad Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HoroscopeRadSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<HoroscopeRadSliceDefaultItem>
>;

/**
 * Slice variation for *HoroscopeRad*
 */
type HoroscopeRadSliceVariation = HoroscopeRadSliceDefault;

/**
 * HoroscopeRad Shared Slice
 *
 * - **API ID**: `horoscope_rad`
 * - **Description**: HoroscopeRad
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HoroscopeRadSlice = prismic.SharedSlice<
  "horoscope_rad",
  HoroscopeRadSliceVariation
>;

/**
 * Primary content in *Members → Items*
 */
export interface MembersSliceDefaultItem {
  /**
   * squadmembers field in *Members → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: members.items[].squadmembers
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  squadmembers: prismic.ContentRelationshipField<
    "squadmembers" | "horoscoperad"
  >;
}

/**
 * Default variation for Members Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MembersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<MembersSliceDefaultItem>
>;

/**
 * Slice variation for *Members*
 */
type MembersSliceVariation = MembersSliceDefault;

/**
 * Members Shared Slice
 *
 * - **API ID**: `members`
 * - **Description**: Members
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MembersSlice = prismic.SharedSlice<
  "members",
  MembersSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      HoroscopeintroductionDocument,
      HoroscopeintroductionDocumentData,
      HoroscoperadDocument,
      HoroscoperadDocumentData,
      SquadmembersDocument,
      SquadmembersDocumentData,
      AllDocumentTypes,
      HoroscopeRadSlice,
      HoroscopeRadSliceDefaultItem,
      HoroscopeRadSliceVariation,
      HoroscopeRadSliceDefault,
      MembersSlice,
      MembersSliceDefaultItem,
      MembersSliceVariation,
      MembersSliceDefault,
    };
  }
}
